# Generated by Django 4.2 on 2024-06-06 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kasten',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('size', models.CharField(choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large')], max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('target_quantity', models.IntegerField(default=1)),
                ('quantity', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('place', models.CharField(max_length=200)),
                ('floor', models.CharField(default='Unknown', max_length=200)),
                ('room', models.CharField(default='Unknown', max_length=200)),
                ('adresse', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=100)),
                ('fk_kasten', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='food.kasten')),
            ],
        ),
        migrations.CreateModel(
            name='KastenProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_quantity', models.IntegerField(default=1)),
                ('quantity', models.IntegerField()),
                ('kasten', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.kasten')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.product')),
            ],
        ),
        migrations.AddField(
            model_name='kasten',
            name='products',
            field=models.ManyToManyField(through='food.KastenProduct', to='food.product'),
        ),
    ]
